In [ ]:
            #    Section 1

# • Import NumPy and math package.
# • Create variables by considering a = 1/√2 and b = 1/√2
# • Create a vector or One-dimensional array using variables a and b.
# • Check whether the vector is normalized or not. Vector is normalized if a**2 + b**2 = 1 in thisparticular case.
# • Find the length of a vector.


import numpy as np
import math
a = 1/math.sqrt(2)
b = 1/math.sqrt(2)
vector = np.array([a,b])
is_normalized = (a**2 + b**2) == 1
length = np.linalg.norm(vector)
print("Vector:", vector)
print("Is the vector normalized?", is_normalized)
print("Length of the vector:", length)

Vector: [0.70710678 0.70710678]
Is the vector normalized? False
Length of the vector: 0.9999999999999999


In [ ]:
                # Section 2

# • Create a vector and read the elements of the vector from the keyboard.
# • Write a function that will check whether the function is normalized or not.
# • Write a function to find the dot and cross product of two vectors (A and B) using NumPy.
# • Write a function to find a unit vector corresponding to vector A.

import numpy as np


def is_normalized(vector):
    magnitude = np.linalg.norm(vector)
    return np.isclose(magnitude, 1)


def dot_and_cross(A, B):
    dot_product = np.dot(A, B)
    cross_product = np.cross(A, B)
    return dot_product, cross_product

def unit_vector(A):
    magnitude = np.linalg.norm(A)
    if magnitude == 0:
        return None
    return A / magnitude

n = int(input("Enter the number of elements in the vector: "))
elements = []

print("Enter the elements:")
for i in range(n):
    elements.append(float(input()))

vector = np.array(elements)

print("\nVector:", vector)
print("Is the vector normalized?", is_normalized(vector))


print("\nEnter elements of vector A (3 elements):")
A = np.array([float(input()) for _ in range(3)])

print("Enter elements of vector B (3 elements):")
B = np.array([float(input()) for _ in range(3)])

dot_product, cross_product = dot_and_cross(A, B)

print("\nDot Product of A and B:", dot_product)
print("Cross Product of A and B:", cross_product)

unit_A = unit_vector(A)

if unit_A is not None:
    print("\nUnit vector corresponding to A:", unit_A)
else:
    print("\nUnit vector cannot be calculated for zero vector.")


Enter the number of elements in the vector: 3
Enter the elements:
1
2
3

Vector: [1. 2. 3.]
Is the vector normalized? False

Enter elements of vector A (3 elements):
1
1
1
Enter elements of vector B (3 elements):
2
2
2

Dot Product of A and B: 6.0
Cross Product of A and B: [0. 0. 0.]

Unit vector corresponding to A: [0.57735027 0.57735027 0.57735027]


In [ ]:
                # Section 3
# • Read a matrix from the Keyboard.
# • Find the transpose of a matrix.
# • Find the Determinant of a matrix ( Using linalg.det in NumPy).
# • Find Rank of a matrix ( Using linalg.matrixrank in numpy).
# • Find Trace of the matrix
# • Find Eigenvalue and Eigenvectors of a square matrix (Use linalg.eig).
# • Find the Inverse of a matrix.

import numpy as np

# Read matrix from keyboard
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print("Enter the elements row-wise:")
matrix = []

for i in range(rows):
    row = [float(input()) for _ in range(cols)]
    matrix.append(row)

A = np.array(matrix)

print("\nMatrix A:")
print(A)

# Transpose of the matrix
transpose = A.T
print("\nTranspose of the matrix:")
print(transpose)

# Determinant (only for square matrix)

if rows == cols:
    determinant = np.linalg.det(A)
    print("\nDeterminant of the matrix:")
    print(determinant)
else:
    print("\nDeterminant cannot be calculated (not a square matrix).")

# Rank of the matrix
rank = np.linalg.matrix_rank(A)
print("\nRank of the matrix:")
print(rank)

# Trace of the matrix (square matrix)
if rows == cols:
    trace = np.trace(A)
    print("\nTrace of the matrix:")
    print(trace)
else:
    print("\nTrace cannot be calculated (not a square matrix).")

# Eigenvalues and Eigenvectors
if rows == cols:
    eigenvalues, eigenvectors = np.linalg.eig(A)
    print("\nEigenvalues:")
    print(eigenvalues)
    print("\nEigenvectors:")
    print(eigenvectors)
else:
    print("\nEigenvalues and Eigenvectors cannot be calculated (not a square matrix).")

# Inverse of the matrix
if rows == cols:
    if np.linalg.det(A) != 0:
        inverse = np.linalg.inv(A)
        print("\nInverse of the matrix:")
        print(inverse)
    else:
        print("\nInverse does not exist (determinant is zero).")
else:
    print("\nInverse cannot be calculated (not a square matrix).")


Enter number of rows: 2
Enter number of columns: 2
Enter the elements row-wise:
1
-1
1
1

Matrix A:
[[ 1. -1.]
 [ 1.  1.]]

Transpose of the matrix:
[[ 1.  1.]
 [-1.  1.]]

Determinant of the matrix:
2.0

Rank of the matrix:
2

Trace of the matrix:
2.0

Eigenvalues:
[1.+1.j 1.-1.j]

Eigenvectors:
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]

Inverse of the matrix:
[[ 0.5  0.5]
 [-0.5  0.5]]


In [ ]:
                #  Section 4
# • Read a complex number from the keyboard.
# • Find the complex conjugate of the complex number.
# • Addition, subtraction, multiplication, and divisions of complex numbers.
# • understands the concept of a complex number as a 2D vector.
# • Find the length or magnitude of a complex number.


import math

# Read complex numbers from the keyboard

real1 = float(input("Enter real part of first complex number: "))
imag1 = float(input("Enter imaginary part of first complex number: "))
z1 = complex(real1, imag1)

real2 = float(input("\nEnter real part of second complex number: "))
imag2 = float(input("Enter imaginary part of second complex number: "))
z2 = complex(real2, imag2)

print("\nFirst Complex Number (z1):", z1)
print("Second Complex Number (z2):", z2)


# Complex conjugate

conjugate_z1 = z1.conjugate()
print("\nComplex Conjugate of z1:", conjugate_z1)

# Arithmetic operations

print("\nAddition (z1 + z2):", z1 + z2)
print("Subtraction (z1 - z2):", z1 - z2)
print("Multiplication (z1 * z2):", z1 * z2)

if z2 != 0:
    print("Division (z1 / z2):", z1 / z2)
else:
    print("Division not possible (z2 = 0)")


# Complex number as a 2D vector

print("\nComplex number as a 2D vector:")
print("z1 → (", z1.real, ",", z1.imag, ")")


# Magnitude (length) of a complex number

magnitude = abs(z1)
print("\nMagnitude (length) of z1:", magnitude)


Enter real part of first complex number: 2
Enter imaginary part of first complex number: -1

Enter real part of second complex number: 1
Enter imaginary part of second complex number: -2

First Complex Number (z1): (2-1j)
Second Complex Number (z2): (1-2j)

Complex Conjugate of z1: (2+1j)

Addition (z1 + z2): (3-3j)
Subtraction (z1 - z2): (1+1j)
Multiplication (z1 * z2): -5j
Division (z1 / z2): (0.8+0.6j)

Complex number as a 2D vector:
z1 → ( 2.0 , -1.0 )

Magnitude (length) of z1: 2.23606797749979
